url: "https://ma-ville-accessible.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/website" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
